$scriptPath = split-path -parent $MyInvocation.MyCommand.Definition

$shaGeneratorPath = Join-Path $scriptPath -ChildPath "tools\sha1deep64.exe"

function sync-folder($folder) {

    $fullPath = Join-Path $scriptPath -ChildPath $folder
    $releaseFilePath = Join-Path $fullPath -ChildPath "RELEASES"
    $releaseFilesSearch = Join-Path $fullPath -ChildPath "*.nupkg"

    $releaseFiles = Get-ChildItem $releaseFilesSearch

    if (Test-Path $releaseFilePath) {
        Remove-Item $releaseFilePath
    }

    "# This file has been generated by a tool. Do not modify" | Out-File $releaseFilePath -Append 
    
    foreach ($release in $releaseFiles) {
        Write-Host $release.FullName
        $programOutput = & $shaGeneratorPath $release.FullName 2>&1 
        $sha = ([regex]"^([0-9a-fA-F]{40})(.*)").match($programOutput).groups[1].value
        $length = (Get-item $release.FullName).length
        $name = $release.Name
        
        "$sha  $name  $length" | Out-File $releaseFilePath -Append 
    }
}


sync-folder "dev"
sync-folder "stable"